version: '2'

services:
    ######################
    # Monitring Services #
    ######################
    cadvisor:
      image: google/cadvisor:latest
      container_name: oai_cadvisor
      ports:
          - 8080:8080
      volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
          - /dev/disk/:/dev/disk:ro
      networks:
          - monitoring
    prometheus:
      image: prom/prometheus
      container_name: oai_prometheus
      ports:
          - 9090:9090
      volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
      networks:
          - monitoring
    grafana:
      image: grafana/grafana
      container_name: oai_grafana
      ports:
          - 3000:3000
      networks:
          - monitoring

    #####################
    # Traffic Generator #
    #####################
    iperf3_server:
      image: networkstatic/iperf3
      container_name: oai_iperf3_server
      ports:
          - 5201:5201
      command: ["-s"]
      networks:
        default:
        epc:
          ipv4_address: 192.168.142.40
    iperf3_client:
      depends_on:
          - iperf3_server
      image: networkstatic/iperf3
      container_name: oai_iperf3_client
      entrypoint: bash -x -c "while true;do /usr/bin/iperf3 -c iperf3_server; sleep 30;done"
      volumes:
       - /tmp/iperf_status:/tmp/iperf_status
      networks:
        epc:

    ###############
    # EPC Network #
    ###############

    ######
    # DB #
    ######
    db:
      build: db
      environment:
          - MYSQL_ROOT_PASSWORD=linux
      networks:
        default:
      volumes:
       - ./db/oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql

    balance_db:
        image: nginx
        networks:
            default:
        ports:
            - 3306:3306
        volumes:
            - ./balance/balance_db.conf:/etc/nginx/nginx.conf
        depends_on:
            - "db"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
       - db:db
      ports:
          - 8088:80
      environment:
          - MYSQL_ROOT_PASSWORD=linux
          - MYSQL_USER=root
          - MYSQL_PASSWORD=linux
    #######
    # HSS #
    #######
    hss:
      build: hss
      volumes:
       - ./hss/hss.conf:/usr/local/etc/oai/hss.conf:ro
      depends_on:
          - "db"
      networks:
        default:
        epc:
          ipv4_address: 192.168.142.10
      domainname: openair4G.eur
      hostname: hss
      ports:
        - 3868:3868

    balance_hss:
        image: nginx
        volumes:
            - ./balance/balance_hss.conf:/etc/nginx/nginx.conf
        depends_on:
            - "hss"
    #######
    # MME #
    #######
    mme:
      build: mme
      volumes:
       - ./mme/mme.conf:/usr/local/etc/oai/mme.conf:ro
      depends_on:
          - "hss"
      networks:
        default:
        epc:
          ipv4_address: 192.168.142.20
      domainname: openair4G.eur
      hostname: mme
      ports:
        - 2123:2123

    balance_mme:
        image: nginx
        volumes:
            - ./balance/balance_mme.conf:/etc/nginx/nginx.conf
        depends_on:
            - "mme"
    ########
    # SPGW #
    ########
    spgw:
      build: spgw
      privileged: true
      volumes:
       - /lib/modules:/lib/modules
       - ./spgw/spgw.conf:/usr/local/etc/oai/spgw.conf:ro
      depends_on:
          - "mme"
      ports:
          - 2152:2152
      networks:
        default:
        epc:
          ipv4_address: 192.168.142.30
      domainname: openair4G.eur
      hostname: spgw

    balance_spgw:
        image: nginx
        volumes:
            - ./balance/balance_spgw.conf:/etc/nginx/nginx.conf
        depends_on:
            - "spgw"

############
# Networks #
############
networks:
  monitoring:
    driver: bridge
  epc:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.142.0/24
          gateway: 192.168.142.1
