version: '2'

services:
  db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=linux
    domainname: openair4G.eur
    hostname: db
    volumes:
        - /etc/oai-docker-conf/oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
     - db:db
    ports:
        - 8080:80
    environment:
        - MYSQL_ROOT_PASSWORD=linux
        - MYSQL_USER=linux
        - MYSQL_PASSWORD=linux
  hss:
    build: hss
    links:
     - db:db.openair4G.eur
    networks:
      default:
      epc:
        ipv4_address: 10.0.5.101
    domainname: openair4G.eur
    hostname: hss
    volumes:
        - /etc/oai-docker-conf:/usr/local/etc/oai
  mme: 
    build: mme
    links:
     - hss:hss.openair4G.eur
    networks:
      epc:
        ipv4_address: 10.0.5.102
    domainname: openair4G.eur
    hostname: mme
    volumes:
        - /etc/oai-docker-conf:/usr/local/etc/oai
  spgw: 
    build: spgw
    links:
     - hss:hss.openair4G.eur
    networks:
      epc:
        ipv4_address: 10.0.5.103
    privileged: true
    domainname: openair4G.eur
    hostname: spgw
    volumes:
     - /lib/modules:/lib/modules 
     - /etc/oai-docker-conf:/usr/local/etc/oai
networks:
  epc:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.5.0/24
          gateway: 10.0.5.1
